- .gitignore
- package-lock.json
- package.json
- src/database/entities/classes.entity.ts
- src/database/entities/reviews.entity.ts
Se crearon las entidades de classes y reviews
> Se agrega la entidad classes y reviews

- src/database/entities/attendance.entity.ts
- src/database/entities/booked_classes.entity.ts
- src/database/entities/classes.entity.ts
- src/database/entities/trainer.entity.ts
- src/enum/bookingStatus.enum.ts
creacion de las entidades boked_class,trainers,attendance
> creacion de las entidades booked_classes,atendance,trainer

- src/database/entities/attendance.entity.ts
- src/database/entities/booked_classes.entity.ts
- src/database/entities/classes.entity.ts
- src/database/entities/membership.entity.ts
- src/database/entities/reviews.entity.ts
- src/database/entities/trainer.entity.ts
- src/enum/bookingStatus.enum.ts
- src/enum/roles.enum.ts
- src/modules/products/products.reposiroty.ts
- src/modules/users/users.repository.ts
> entity-membership

- .eslintrc.js
- src/database/entities/user.entity.ts
- src/enum/membership_status.enum.ts
added user entity, membership_status enum and configured .eslintrc.js
> added user entity, membership_status enum and configured .eslintrc.js

- src/app.module.ts
- src/modules/auth/auth.controller.ts
- src/modules/auth/auth.service.ts
- src/modules/classes/classes.controller.ts
- src/modules/classes/classes.module.ts
- src/modules/classes/classes.service.ts
- src/modules/reviews/reviews.controller.ts
- src/modules/reviews/reviews.module.ts
- src/modules/reviews/reviews.service.ts
Se agregan modulo classes y reviews, con sus respectivos controladores y servicios, se crean endpoits en reviews y se modifican importaciones ya no existentes de los dto en auth
> Se agregan cambios, creacion carpeta classes y Reviews

- src/app.module.ts
- src/database/entities/booked_classes.entity.ts
- src/database/entities/membership.entity.ts
- src/database/entities/reviews.entity.ts
- src/database/entities/trainer.entity.ts
- src/database/entities/user.entity.ts
- src/enum/roles.enum.ts
- src/modules/auth/auth.controller.ts
- src/modules/auth/auth.service.ts
- src/modules/classes/classes.module.ts
- src/modules/reviews/reviews.controller.ts
- src/modules/reviews/reviews.module.ts
- src/modules/reviews/reviews.service.ts
trying to solve merge conflict before merging with main
> Solving merge conflict

- src/enum/roles.enum.ts
> Merge dev to main

- src/app.module.ts
- src/modules/attendance/attendance.controller.ts
- src/modules/attendance/attendance.repository.ts
- src/modules/attendance/attendance.service.ts
- src/modules/booked_classes/booked_classes.controller.ts
- src/modules/booked_classes/booked_classes.repository.ts
- src/modules/booked_classes/booked_classes.service.ts
- src/modules/payments/payments.controller.ts
- src/modules/payments/payments.repository.ts
- src/modules/payments/payments.service.ts
creacion de controller,service y repository en modules/payments modules/booked_classes y  modules/attendance
> creacion de rutas y metodos de booked_classes-attendance-payments

- src/database/entities/payment.entity.ts
> payments-harrison

- .editorconfig
- .prettierrc
- src/database/entities/payment.entity.ts
- src/database/entities/reviews.entity.ts
- src/database/entities/trainer.entity.ts
- src/database/entities/user.entity.ts
added .editorconfig to have a persistent config about CRLF
> added .editorconfig to have a persistent config about CRLF

- src/modules/trainer/dto/create-trainer.dto.ts
- src/modules/trainer/trainer.controller.ts
- src/modules/trainer/trainer.module.ts
- src/modules/trainer/trainer.service.ts
Se realiza crean los archivos sobre 
Version (bf413d0) de rama dev
> Creacion de controller/module/service/create-trainer.dto Harrison

- src/database/entities/user.entity.ts
- src/interceptors/userPasswordRemoval.interceptor.ts
- src/main.ts
- src/middlewares/UsersLogger.middleware.ts
- src/modules/users/users.controller.ts
- src/modules/users/users.module.ts
- src/modules/users/users.repository.ts
- src/modules/users/users.service.ts
FEATURE:
1. added endpoint logger middleware which logs on console each HTTP request.
2. added  an interceptor which removes passwords when requesting info to hide sensitive data
3. implemented onModuleInit hook to control nestj lifecycle to seed database with users.
> FEATURE: middleware to log HTTTP requests, interceptor to remove passwords, Database's seeding with user's information.

- src/database/entities/classes.entity.ts
- src/utils/mockeClass.json
- src/utils/seederClass.ts
se añadio a la carpeta utils los archivos mockeClass y seederClass
> creacion de seeder para class

- src/decorators/roles.decorator.ts
- src/modules/auth/auth.service.ts
- src/modules/booked_classes/booked_classes.controller.ts
- src/modules/classes/classes.controller.ts
- src/modules/payments/payments.controller.ts
- src/modules/payments/payments.repository.ts
- src/modules/payments/payments.service.ts
- src/modules/products/products.controller.ts
- src/modules/products/products.service.ts
- src/modules/reviews/reviews.controller.ts
- src/modules/reviews/reviews.service.ts
- src/modules/trainers/trainers.controller.ts
- src/modules/trainers/trainers.service.ts
- src/modules/users/users.controller.ts
- src/modules/users/users.service.ts
Se añaden async await en todos los modulos, podria ser que falte en alguno que otro favor de checar
> Pestañeo de async await

- package-lock.json
- package.json
- src/modules/auth/auth.controller.ts
- src/modules/auth/auth.service.ts
- src/modules/users/users.repository.ts
- src/modules/users/users.service.ts
creacion de de singinIn de users con validacion de jwt
> creacion de singIg con jwt

- src/utils/mock-trainers.json
Se realiza la creación del mockup de trainers se ejecuta sobre "dev" versión (e3b56ff)
> Creacion mockup-trainers hdeviam

- src/database/entities/trainer.entity.ts
- src/database/entities/user.entity.ts
- src/modules/trainers/trainers.repository.ts
Implementing trainers seeding logic to project.
> UPDATE: Implementing trainers seeding logic

- src/database/entities/user.entity.ts
- src/modules/classes/classes.repository.ts
changed some token names to load class entity properly.
> FIX: changed some token names to load class entity properly.

- package-lock.json
- package.json
- src/database/config/typeorm.ts
- src/database/entities/user.entity.ts
- src/main.ts
- src/modules/classes/classes.repository.ts
- src/modules/users/dto/create-user.dto.ts
- src/modules/users/dto/updateUser.dto.ts
- src/modules/users/users.repository.ts
- src/pipes/cleanName.pipe.ts
setting cors to allow incomig request from a frontend app to test fullstack app. Changed properties firstName and lastName and unified them into name. Changed regex to allow an easier password for new users.
> FIX: setting cors and modifying database properties and DTO for easier password validations.

- .github/CODEOWNERS
> newCodeOwner

- src/modules/users/users.repository.ts
se modifico el metodo updateUser en users.repository.ts
> modificacion en la actualizacion del los usuarios

- src/modules/classes/classes.controller.ts
se cambio el paginado de class de 5 a 6
> cambio del paginado de clases

- src/database/config/typeorm.ts
- src/modules/booked_classes/booked_classes.controller.ts
- src/modules/booked_classes/booked_classes.module.ts
- src/modules/booked_classes/booked_classes.repository.ts
- src/modules/booked_classes/booked_classes.service.ts
- src/modules/booked_classes/dto/createBookedDto.ts
- src/modules/email/email.service.ts
se crearon las funcionalidades para reservas y un mail de confirmacion cuando se crea o elimina una reserva
> crud de reservas y mails de confirmacion

- src/modules/classes/classes.repository.ts
- src/utils/mock-users.json
- src/utils/mockeClass.json
FIX: classes seeding logic. Populated user's database with more data points
> FIX: classes seeding logic. Populated user's database with more data points

- src/database/entities/payment.entity.ts
- src/modules/memberships/memberships.module.ts
- src/modules/payments/payments.controller.ts
- src/modules/payments/payments.module.ts
- src/modules/payments/payments.repository.ts
- src/modules/payments/payments.service.ts
- src/modules/users/users.module.ts
Se actualiza el endpoint para guardar datos en la base de datos, asi como el cambio de estatus en la base de datos del usurario despues del pago
> almacenamiento en la base de datos con stripe

- src/database/entities/user.entity.ts
- src/enum/status.enum.ts
- src/interceptors/addJWT.interceptor.ts
- src/modules/auth/auth.controller.ts
- src/modules/auth/auth.module.ts
- src/modules/auth/auth.repository.ts
- src/modules/auth/auth.service.ts
- src/modules/auth/dto/auth0-logIn.dto.ts
- src/modules/auth/jsonWebToken.service.ts
- src/modules/email/email.module.ts
- src/modules/email/email.service.ts
- src/modules/users/dto/updateUser.dto.ts
- src/utils/mock-users.json
incomplete third party signUp and signUp logic.
> FEATURE: incomplete third party signUp and signUp logic

- src/database/entities/ClassSchedule.entity.ts
- src/database/entities/booked_classes.entity.ts
- src/database/entities/classes.entity.ts
- src/modules/booked_classes/booked_classes.controller.ts
- src/modules/booked_classes/booked_classes.module.ts
- src/modules/booked_classes/booked_classes.repository.ts
- src/modules/booked_classes/booked_classes.service.ts
- src/modules/booked_classes/dto/createBookedDto.ts
- src/modules/classes/classes.controller.ts
- src/modules/classes/classes.module.ts
- src/modules/classes/classes.repository.ts
- src/modules/classes/classes.service.ts
- src/modules/classes/dto/create-classes.dto.ts
- src/modules/classes/dto/createSchedule.dto.ts
- src/modules/classes/dto/update-classes.dto.ts
- src/modules/classes/dto/updateSchedule.dto.ts
- src/modules/email/email.service.ts
- src/modules/trainers/trainers.repository.ts
- src/utils/mockeClass.json
cambios en la logica de class y booked_class(entity,dtos,repositorys,services y controllers)
> cambios en clases y booked_class

- src/database/entities/reviews.entity.ts
- src/modules/classes/classes.module.ts
- src/modules/reviews/dto/create-review.dto.ts
- src/modules/reviews/reviews.controller.ts
- src/modules/reviews/reviews.module.ts
- src/modules/reviews/reviews.service.ts
creación de reviews controllers, module, service, create-review.dto
> reviews-hdeviam

- src/database/entities/user.entity.ts
- src/interceptors/addJWT.interceptor.ts
- src/modules/auth/auth.controller.ts
- src/modules/auth/auth.service.ts
- src/modules/users/users.service.ts
> FIX: auth logic working

- src/modules/auth/auth.service.ts
- src/modules/users/users.controller.ts
- src/modules/users/users.service.ts
FIX: auth logic for third party based sign up and form-based sign up successfully working.
> FIX: auth logic for third party based sign up and form-based sign up successfully working.
